### ISSUE TITLE
HF dataset reader

### ISSUE THREAD

**Issue by leonhardhennig** [suamin/MedDistant19#2]
Hi Saad,
is there a HF dataset reader for this dataset ? If not - would you mind if we implement it, similar to https://huggingface.co/datasets/DFKI-SLT/tacred ?  (i.e. loading script + URL pointers to the downloads and License notification)
Leo

**Comment by suamin** [comment]
Hi Leo,

The dataset was designed to be compatiable with [OpenNRE](https://github.com/thunlp/OpenNRE) format, which expects train-dev-test split with each line a json as follows:

````json
{
    "text": "Urethral stones are rarely formed primarily in the urethra and are usually associated with urethral strictures or diverticula .", 
    "h": {"id": "C0041967", "pos": [51, 58], "name": "urethra"}, 
    "t": {"id": "C0041974", "pos": [91, 110], "name": "urethral strictures"}, 
    "relation": "finding_site_of"
}
````

Since OpenNRE is commonly used in community, this allowed MedDistant19 to be directly usable by the framework. 

A HF dataset reader sounds like a great contribution 🙂 thank you! Kindly feel free to post here further if you run into issues.

Best, 
Saad

**Comment by leonhardhennig** [comment]
Great, thanks. It will be available at https://huggingface.co/datasets/DFKI-SLT/MedDistant19 .
Best, Leo

**Comment by suamin** [comment]
FYI @pminervini

**Comment by pminervini** [comment]
Amazing, thank you! 🙂
